services:
  doh-server:
    image: satishweb/doh-server:latest
    container_name: doh-server
    hostname: doh-server
    networks:
      - dokploy-network
    environment:
      # Enable below line to see more logs
      DEBUG: "1"
      UPSTREAM_DNS_SERVER: "udp:1.1.1.1:53"
      DOH_HTTP_PREFIX: "${DOH_HTTP_PREFIX}"
      DOH_SERVER_LISTEN: ":${DOH_SERVER_LISTEN}"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
    expose:
      - "${DOH_SERVER_LISTEN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doh-server.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`${DOH_HTTP_PREFIX}`)"
      - "traefik.http.services.doh-server.loadbalancer.server.port=${DOH_SERVER_LISTEN}"
      - "traefik.http.routers.doh-server.tls=true"
      - "traefik.http.routers.doh-server.tls.certresolver=letsencrypt"
      - "traefik.http.routers.doh-server.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.doh-server.tls.domains[0].sans=${SUBDOMAIN}.${DOMAIN}"
      # Define middlewares
      - "traefik.http.middlewares.doh-compression.compress=true"
      - "traefik.http.middlewares.doh-tls.headers.sslredirect=true"
      - "traefik.http.middlewares.doh-tls.headers.sslforcehost=true"
      # Apply middlewares
      - "traefik.http.routers.doh-server.middlewares=doh-compression,doh-tls,doh-ratelimit"
      # Protection from requests flood
      - "traefik.http.middlewares.doh-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.doh-ratelimit.ratelimit.burst=50"
      - "traefik.http.middlewares.doh-ratelimit.ratelimit.period=10s"

networks:
  dokploy-network:
    external: true