services:
  doh-server:
    image: satishweb/doh-server:latest
    hostname: doh-server
    restart: unless-stopped
    networks:
      - dokploy-network
    volumes:
      - ./doh-server.conf:/doh-server.conf
    command: ["/server/doh-server", "-conf", "/doh-server.conf"]
    expose:
      - "8053"
    labels:
      - traefik.enable=true
      
      # -- ROUTING --
      - traefik.http.routers.doh-server.rule=Host(`resolver.${DOMAIN}`) && PathPrefix(`${DOH_HTTP_PREFIX}`)
      - traefik.http.routers.doh-server.entrypoints=websecure
      - traefik.http.routers.doh-server.service=doh-server
      - traefik.http.services.doh-server.loadbalancer.server.port=8053
      
      # -- TLS --
      - traefik.http.routers.doh-server.tls=true
      - traefik.http.routers.doh-server.tls.certresolver=letsencrypt
      
      # -- AUTHENTICATION --
      # Combines username + bcrypt hash from .env
      # The hash is injected via ${} substitution — no $$ escaping needed here.
      # Generate hash: htpasswd -Bbn myuser mypassword
      - traefik.http.middlewares.doh-auth.basicauth.users=${DOH_USER}:${DOH_HASHED_PASS}
      
      # -- MIDDLEWARES --
      - traefik.http.middlewares.doh-compression.compress=true
      - traefik.http.middlewares.doh-tls.headers.sslredirect=true
      - traefik.http.middlewares.doh-tls.headers.sslforcehost=true
      
      # Ratelimit
      - traefik.http.middlewares.doh-ratelimit.ratelimit.average=200
      - traefik.http.middlewares.doh-ratelimit.ratelimit.burst=100
      - traefik.http.middlewares.doh-ratelimit.ratelimit.period=10s

      # Apply all middlewares
      - traefik.http.routers.doh-server.middlewares=doh-compression,doh-tls,doh-ratelimit,doh-auth

networks:
  dokploy-network:
    external: true
